version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  ollama:
    image: ollama/ollama
    container_name: ollama
    expose:
      - 11434